import type {
  Location,
  PortCall,
  TripData,
  TripDay,
} from '../../domain/trip/tripTypes.js'
import { oceaniaMarinaMealRestaurants } from './mealRestaurants.js'
import { oceaniaMarinaActivityLocations } from './activityLocations.js'

// Public cruise dates, ports, and published arrival/departure times:
// https://www.oceaniacruises.com/cruises/MNA260823/
const locations: Location[] = [
  {
    id: 'location-home-ghent',
    name: 'Home',
    city: 'Ghent',
    country: 'Belgium',
  },
  {
    id: 'location-brussels-airport',
    name: 'Brussels Airport (BRU)',
    city: 'Brussels',
    country: 'Belgium',
  },
  {
    id: 'location-keflavik-airport',
    name: 'Keflavík International Airport (KEF)',
    city: 'Keflavík',
    country: 'Iceland',
  },
  {
    id: 'location-hotel-viking',
    name: 'Hotel Viking',
    city: 'Hafnarfjörður',
    country: 'Iceland',
  },
  {
    id: 'location-reykjavik-cruise-terminal',
    name: 'Oceania Marina cruise terminal',
    city: 'Reykjavík',
    country: 'Iceland',
  },
  {
    id: 'location-heathrow-terminal-5',
    name: 'Heathrow Airport Terminal 5',
    city: 'London',
    country: 'United Kingdom',
  },
  { id: 'location-reykjavik', name: 'Reykjavík', city: 'Reykjavík', country: 'Iceland' },
  { id: 'location-isafjordur', name: 'Ísafjörður', city: 'Ísafjörður', country: 'Iceland' },
  { id: 'location-husavik', name: 'Húsavík', city: 'Húsavík', country: 'Iceland' },
  { id: 'location-djupivogur', name: 'Djúpivogur', city: 'Djúpivogur', country: 'Iceland' },
  { id: 'location-torshavn', name: 'Tórshavn', city: 'Tórshavn', country: 'Faroe Islands' },
  { id: 'location-stornoway', name: 'Stornoway (Hebrides)', city: 'Stornoway', country: 'Scotland' },
  { id: 'location-greenock', name: 'Glasgow (Greenock)', city: 'Greenock', country: 'United Kingdom' },
  { id: 'location-dun-laoghaire', name: 'Dublin (Dún Laoghaire)', city: 'Dún Laoghaire', country: 'Ireland' },
  { id: 'location-holyhead', name: 'Holyhead', city: 'Holyhead', country: 'United Kingdom' },
  { id: 'location-ringaskiddy', name: 'Cork (Ringaskiddy)', city: 'Ringaskiddy', country: 'Ireland' },
  { id: 'location-falmouth', name: 'Falmouth', city: 'Falmouth', country: 'United Kingdom' },
  { id: 'location-southampton', name: 'London (Southampton)', city: 'Southampton', country: 'United Kingdom' },
]

// All-aboard values are intentionally absent until verified from an
// authoritative trip document or an onboard source. Oceania confirmed that
// Stornoway replaced the former Portree call on 29 August 2026.
const portCalls: PortCall[] = [
  {
    id: 'port-call-reykjavik',
    dayId: 'day-2026-08-23',
    portLocationId: 'location-reykjavik',
    timeZone: 'Atlantic/Reykjavik',
    arrivalAt: '2026-08-23T07:00:00Z',
    departureAt: '2026-08-23T19:00:00Z',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-embarkation'],
  },
  {
    id: 'port-call-isafjordur',
    dayId: 'day-2026-08-24',
    portLocationId: 'location-isafjordur',
    timeZone: 'Atlantic/Reykjavik',
    arrivalAt: '2026-08-24T09:00:00Z',
    departureAt: '2026-08-24T18:00:00Z',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: ['event-isafjordur-whale-nature'],
  },
  {
    id: 'port-call-husavik',
    dayId: 'day-2026-08-25',
    portLocationId: 'location-husavik',
    timeZone: 'Atlantic/Reykjavik',
    arrivalAt: '2026-08-25T07:00:00Z',
    departureAt: '2026-08-25T16:00:00Z',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: [
      'event-husavik-outbound-tender-report',
      'event-husavik-outbound-tender-departure',
      'event-husavik-shore-arrival',
      'event-husavik-big-whale-safari',
      'event-husavik-whale-boarding',
      'event-husavik-geosea-baths',
      'event-husavik-return-tender-boarding',
      'event-husavik-return-tender-departure',
      'event-husavik-back-onboard',
      'event-husavik-last-tender',
    ],
  },
  {
    id: 'port-call-djupivogur',
    dayId: 'day-2026-08-26',
    portLocationId: 'location-djupivogur',
    timeZone: 'Atlantic/Reykjavik',
    arrivalAt: '2026-08-26T07:00:00Z',
    departureAt: '2026-08-26T16:00:00Z',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: ['event-djupivogur-glacier-lagoon'],
  },
  {
    id: 'port-call-torshavn',
    dayId: 'day-2026-08-27',
    portLocationId: 'location-torshavn',
    timeZone: 'Atlantic/Faroe',
    arrivalAt: '2026-08-27T11:00:00+01:00',
    departureAt: '2026-08-27T20:30:00+01:00',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-torshavn-vestmanna'],
  },
  {
    id: 'port-call-stornoway',
    dayId: 'day-2026-08-29',
    portLocationId: 'location-stornoway',
    timeZone: 'Europe/London',
    arrivalAt: '2026-08-29T07:00:00+01:00',
    departureAt: '2026-08-29T16:00:00+01:00',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: ['event-stornoway-isle-of-lewis'],
  },
  {
    id: 'port-call-greenock',
    dayId: 'day-2026-08-30',
    portLocationId: 'location-greenock',
    timeZone: 'Europe/London',
    arrivalAt: '2026-08-30T10:30:00+01:00',
    departureAt: '2026-08-30T19:30:00+01:00',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-greenock-loch-lomond'],
  },
  {
    id: 'port-call-dun-laoghaire',
    dayId: 'day-2026-08-31',
    portLocationId: 'location-dun-laoghaire',
    timeZone: 'Europe/Dublin',
    arrivalAt: '2026-08-31T08:00:00+01:00',
    departureAt: '2026-08-31T20:00:00+01:00',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: ['event-dublin-river-cruise'],
  },
  {
    id: 'port-call-holyhead',
    dayId: 'day-2026-09-01',
    portLocationId: 'location-holyhead',
    timeZone: 'Europe/London',
    arrivalAt: '2026-09-01T07:00:00+01:00',
    departureAt: '2026-09-01T17:00:00+01:00',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-holyhead-penrhyn-castle'],
  },
  {
    id: 'port-call-ringaskiddy',
    dayId: 'day-2026-09-02',
    portLocationId: 'location-ringaskiddy',
    timeZone: 'Europe/Dublin',
    arrivalAt: '2026-09-02T07:00:00+01:00',
    departureAt: '2026-09-02T17:00:00+01:00',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-cork-jameson'],
  },
  {
    id: 'port-call-falmouth',
    dayId: 'day-2026-09-03',
    portLocationId: 'location-falmouth',
    timeZone: 'Europe/London',
    arrivalAt: '2026-09-03T07:00:00+01:00',
    departureAt: '2026-09-03T16:00:00+01:00',
    portAccess: { status: 'TENDER_REQUIRED' },
    eventIds: ['event-falmouth-st-ives'],
  },
  {
    id: 'port-call-southampton',
    dayId: 'day-2026-09-04',
    portLocationId: 'location-southampton',
    timeZone: 'Europe/London',
    arrivalAt: '2026-09-04T06:00:00+01:00',
    portAccess: { status: 'DOCKED' },
    eventIds: ['event-disembarkation'],
  },
]

const days: TripDay[] = [
  {
    id: 'day-2026-08-22',
    localDate: '2026-08-22',
    startsAt: '2026-08-21T22:00:00Z',
    endsAt: '2026-08-23T00:00:00Z',
    timeZone: 'Europe/Brussels',
    kind: 'DEPARTURE_DAY',
    title: 'Travel to Reykjavík',
    summary: 'Departure journey',
    eventIds: [
      'event-home-brussels-transfer',
      'event-outbound-flight',
      'event-keflavik-hotel-transfer',
      'event-hotel-viking-stay',
    ],
  },
  {
    id: 'day-2026-08-23',
    localDate: '2026-08-23',
    startsAt: '2026-08-23T00:00:00Z',
    endsAt: '2026-08-24T00:00:00Z',
    timeZone: 'Atlantic/Reykjavik',
    kind: 'PORT_DAY',
    title: 'Reykjavík',
    summary: 'Iceland',
    eventIds: [
      'event-hotel-ship-transfer',
      'event-embarkation',
      'event-embarkation-lunch',
    ],
    portCallId: 'port-call-reykjavik',
  },
  {
    id: 'day-2026-08-24',
    localDate: '2026-08-24',
    startsAt: '2026-08-24T00:00:00Z',
    endsAt: '2026-08-25T00:00:00Z',
    timeZone: 'Atlantic/Reykjavik',
    kind: 'PORT_DAY',
    title: 'Ísafjörður',
    summary: 'Iceland',
    eventIds: ['event-isafjordur-whale-nature'],
    portCallId: 'port-call-isafjordur',
  },
  {
    id: 'day-2026-08-25',
    localDate: '2026-08-25',
    startsAt: '2026-08-25T00:00:00Z',
    endsAt: '2026-08-26T00:00:00Z',
    timeZone: 'Atlantic/Reykjavik',
    kind: 'PORT_DAY',
    title: 'Húsavík',
    summary: 'Iceland',
    eventIds: [
      'event-husavik-outbound-tender-report',
      'event-husavik-outbound-tender-departure',
      'event-husavik-shore-arrival',
      'event-husavik-big-whale-safari',
      'event-husavik-whale-boarding',
      'event-husavik-geosea-baths',
      'event-husavik-return-tender-boarding',
      'event-husavik-return-tender-departure',
      'event-husavik-back-onboard',
      'event-husavik-last-tender',
      'event-toscana-dinner',
    ],
    portCallId: 'port-call-husavik',
  },
  {
    id: 'day-2026-08-26',
    localDate: '2026-08-26',
    startsAt: '2026-08-26T00:00:00Z',
    endsAt: '2026-08-26T23:00:00Z',
    timeZone: 'Atlantic/Reykjavik',
    kind: 'PORT_DAY',
    title: 'Djúpivogur',
    summary: 'Iceland',
    eventIds: ['event-djupivogur-glacier-lagoon'],
    portCallId: 'port-call-djupivogur',
  },
  {
    id: 'day-2026-08-27',
    localDate: '2026-08-27',
    startsAt: '2026-08-26T23:00:00Z',
    endsAt: '2026-08-27T23:00:00Z',
    timeZone: 'Atlantic/Faroe',
    kind: 'PORT_DAY',
    title: 'Tórshavn',
    summary: 'Faroe Islands',
    eventIds: ['event-torshavn-vestmanna'],
    portCallId: 'port-call-torshavn',
  },
  {
    id: 'day-2026-08-28',
    localDate: '2026-08-28',
    startsAt: '2026-08-27T23:00:00Z',
    endsAt: '2026-08-28T23:00:00Z',
    timeZone: 'Atlantic/Faroe',
    kind: 'SEA_DAY',
    title: 'At sea',
    summary: 'A relaxed day aboard Oceania Marina',
    eventIds: ['event-red-ginger-dinner'],
  },
  {
    id: 'day-2026-08-29',
    localDate: '2026-08-29',
    startsAt: '2026-08-28T23:00:00Z',
    endsAt: '2026-08-29T23:00:00Z',
    timeZone: 'Europe/London',
    kind: 'PORT_DAY',
    title: 'Stornoway',
    summary: 'Scotland',
    eventIds: ['event-stornoway-isle-of-lewis'],
    portCallId: 'port-call-stornoway',
  },
  {
    id: 'day-2026-08-30',
    localDate: '2026-08-30',
    startsAt: '2026-08-29T23:00:00Z',
    endsAt: '2026-08-30T23:00:00Z',
    timeZone: 'Europe/London',
    kind: 'PORT_DAY',
    title: 'Glasgow (Greenock)',
    summary: 'United Kingdom',
    eventIds: ['event-greenock-loch-lomond'],
    portCallId: 'port-call-greenock',
  },
  {
    id: 'day-2026-08-31',
    localDate: '2026-08-31',
    startsAt: '2026-08-30T23:00:00Z',
    endsAt: '2026-08-31T23:00:00Z',
    timeZone: 'Europe/Dublin',
    kind: 'PORT_DAY',
    title: 'Dublin (Dún Laoghaire)',
    summary: 'Ireland',
    eventIds: ['event-dublin-river-cruise', 'event-polo-grill-dinner'],
    portCallId: 'port-call-dun-laoghaire',
  },
  {
    id: 'day-2026-09-01',
    localDate: '2026-09-01',
    startsAt: '2026-08-31T23:00:00Z',
    endsAt: '2026-09-01T23:00:00Z',
    timeZone: 'Europe/London',
    kind: 'PORT_DAY',
    title: 'Holyhead',
    summary: 'United Kingdom',
    eventIds: ['event-holyhead-penrhyn-castle'],
    portCallId: 'port-call-holyhead',
  },
  {
    id: 'day-2026-09-02',
    localDate: '2026-09-02',
    startsAt: '2026-09-01T23:00:00Z',
    endsAt: '2026-09-02T23:00:00Z',
    timeZone: 'Europe/Dublin',
    kind: 'PORT_DAY',
    title: 'Cork (Ringaskiddy)',
    summary: 'Ireland',
    eventIds: ['event-cork-jameson'],
    portCallId: 'port-call-ringaskiddy',
  },
  {
    id: 'day-2026-09-03',
    localDate: '2026-09-03',
    startsAt: '2026-09-02T23:00:00Z',
    endsAt: '2026-09-03T23:00:00Z',
    timeZone: 'Europe/London',
    kind: 'PORT_DAY',
    title: 'Falmouth',
    summary: 'United Kingdom',
    eventIds: ['event-falmouth-st-ives', 'event-jacques-dinner'],
    portCallId: 'port-call-falmouth',
  },
  {
    id: 'day-2026-09-04',
    localDate: '2026-09-04',
    startsAt: '2026-09-03T23:00:00Z',
    endsAt: '2026-09-04T23:00:00Z',
    timeZone: 'Europe/London',
    kind: 'FINAL_TRAVEL_DAY',
    title: 'Southampton → Home',
    summary: 'Disembarkation and journey home',
    eventIds: [
      'event-disembarkation-breakfast',
      'event-disembarkation-cabin-vacate',
      'event-disembarkation-group',
      'event-disembarkation',
      'event-southampton-heathrow-transfer',
      'event-heathrow-arrival-estimate',
      'event-heathrow-bag-drop',
      'event-heathrow-security',
      'event-return-flight',
    ],
    portCallId: 'port-call-southampton',
  },
]

export const oceaniaMarina2026TripData: TripData = {
  schemaVersion: 1,
  dataVersion: '2026-07-31.2',
  publishedAt: '2026-07-31T16:00:00Z',
  trip: {
    id: 'trip-oceania-marina-2026',
    title: 'Iceland & British Isles',
    startDate: '2026-08-22',
    endDate: '2026-09-04',
    homeTimeZone: 'Europe/Brussels',
    travelerIds: ['traveler-yoav', 'traveler-isabel'],
    dayIds: days.map(({ id }) => id),
    cruiseId: 'cruise-oceania-marina-2026',
    welcomeHeroImage:
      '/images/oceania-marina-welcome-hero-portrait.jpg',
  },
  travelers: [
    { id: 'traveler-yoav', displayName: 'Yoav' },
    { id: 'traveler-isabel', displayName: 'Isabel' },
  ],
  days,
  mealRestaurants: [...oceaniaMarinaMealRestaurants],
  activityLocations: [...oceaniaMarinaActivityLocations],
  events: [
    {
      id: 'event-home-brussels-transfer',
      dayId: 'day-2026-08-22',
      kind: 'TRANSFER',
      title: 'Home to Brussels Airport',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-08-22T10:30:00+02:00',
      endsAt: '2026-08-22T11:30:00+02:00',
      timeZone: 'Europe/Brussels',
      locationId: 'location-home-ghent',
      transportId: 'transport-home-brussels-airport',
      bookingStatus: 'CONFIRMED',
      leaveByAt: '2026-08-22T10:30:00+02:00',
      meetingContext: 'Burgstraat 35, Gent',
      operationalNotes: [
        'Anaïs is the confirmed driver.',
        'Target arrival at Brussels Airport: 11:30.',
        'Airport drop-off; no parking required.',
      ],
    },
    {
      id: 'event-outbound-flight',
      dayId: 'day-2026-08-22',
      kind: 'FLIGHT',
      title: 'Flight to Keflavík',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-08-22T13:50:00+02:00',
      endsAt: '2026-08-22T15:10:00Z',
      timeZone: 'Europe/Brussels',
      endTimeZone: 'Atlantic/Reykjavik',
      locationId: 'location-brussels-airport',
      transportId: 'transport-outbound-flight',
      organizer: 'Icelandair',
      publicCode: 'FI555',
      bookingStatus: 'CONFIRMED',
      operationalNotes: [
        'Saga Premium · Isabel seat 03D · Yoav seat 03F.',
        'Check the Icelandair app for gate and final boarding time.',
        'Checked baggage: 2 × 32 kg per person.',
        'Carry-on: 1 × 10 kg per person.',
        'Personal item maximum: 40 × 30 × 15 cm.',
      ],
    },
    {
      id: 'event-keflavik-hotel-transfer',
      dayId: 'day-2026-08-22',
      kind: 'TRANSFER',
      title: 'Flybus to Hotel Viking',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-keflavik-airport',
      transportId: 'transport-keflavik-hotel',
      organizer: 'Reykjavík Excursions / Flybus',
      bookingStatus: 'CONFIRMED',
      scheduleStatus: 'TO_BE_CONFIRMED',
      travelDurationRangeMinutes: {
        minimum: 40,
        maximum: 45,
      },
      travelDurationVerification: 'ESTIMATED',
      estimatedSchedule: {
        anchorEventId: 'event-outbound-flight',
        startOffsetMinutes: {
          minimum: 35,
          maximum: 40,
        },
      },
      meetingContext: 'Outside the KEF Arrivals exit',
      operationalNotes: [
        'Flexible ticket for 2 adults.',
        'Buses normally leave 35–40 minutes after each arriving flight.',
        'Destination stop: Fjörukráin, Hafnarfjörður.',
        'No exact departure time is confirmed.',
      ],
      documentReferenceIds: ['document-keflavik-reykjavik-flybus'],
    },
    {
      id: 'event-hotel-viking-stay',
      dayId: 'day-2026-08-22',
      kind: 'HOTEL_STAY',
      title: 'Hotel Viking',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-08-22T16:00:00Z',
      endsAt: '2026-08-23T11:00:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-hotel-viking',
      bookingStatus: 'CONFIRMED',
      meetingContext: 'Strandgata 55, 220 Hafnarfjörður, Iceland',
      operationalNotes: [
        'Check-in from 16:00; latest stated check-in is 00:00.',
        'Check-out by 11:00.',
        'Standard Double Room · 2 adults · breakfast included.',
      ],
      documentReferenceIds: ['document-precruise-hotel'],
    },
    {
      id: 'event-hotel-ship-transfer',
      dayId: 'day-2026-08-23',
      kind: 'TRANSFER',
      title: 'Hotel Viking to Oceania Marina',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-08-23T12:00:00Z',
      endsAt: '2026-08-23T12:30:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-hotel-viking',
      transportId: 'transport-hotel-ship',
      timingVerification: 'ESTIMATED',
      meetingContext:
        'Hotel Viking lobby · exact Reykjavík berth to be confirmed',
      operationalNotes: [
        'Planning estimate; keep this time editable in Trip.',
        'Temporary destination: Marina cruise terminal, Reykjavík.',
        'Exact berth remains to be confirmed.',
      ],
    },
    {
      id: 'event-embarkation',
      dayId: 'day-2026-08-23',
      kind: 'EMBARKATION',
      title: 'Embark Oceania Marina',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-08-23T13:00:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-reykjavik-cruise-terminal',
      timingVerification: 'CONFIRMED',
      meetingContext: 'Exact cruise terminal to be confirmed',
      operationalNotes: [
        'Embarkation starts at 13:00; target arrival at the dock is 13:00.',
        'Plan is to board in time for lunch on the ship.',
        'Latest permitted boarding time is not yet confirmed.',
        'Stateroom: 10038.',
      ],
    },
    {
      id: 'event-embarkation-lunch',
      dayId: 'day-2026-08-23',
      kind: 'MEAL',
      title: 'Lunch onboard',
      startsAt: '2026-08-23T13:30:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-reykjavik-cruise-terminal',
      timingVerification: 'ESTIMATED',
      operationalNotes: [
        'Planning intention after boarding; keep this time editable in Trip.',
      ],
    },
    {
      id: 'event-disembarkation-breakfast',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Breakfast opens',
      timeZone: 'Europe/London',
      locationId: 'location-southampton',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-disembarkation-cabin-vacate',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Cabin must be vacated',
      timeZone: 'Europe/London',
      locationId: 'location-southampton',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-disembarkation-group',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Disembarkation group called',
      timeZone: 'Europe/London',
      locationId: 'location-southampton',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-disembarkation',
      dayId: 'day-2026-09-04',
      kind: 'DISEMBARKATION',
      title: 'Leave ship',
      timeZone: 'Europe/London',
      locationId: 'location-southampton',
      scheduleStatus: 'TO_BE_CONFIRMED',
      operationalNotes: [
        'Oceania Marina is scheduled to arrive at 06:00.',
        'Disembarkation clearance time is not yet confirmed.',
      ],
    },
    {
      id: 'event-southampton-heathrow-transfer',
      dayId: 'day-2026-09-04',
      kind: 'TRANSFER',
      title: 'Southampton to Heathrow Terminal 5',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-09-04T07:45:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-southampton',
      transportId: 'transport-southampton-heathrow',
      bookingStatus: 'CONFIRMED',
      meetingContext:
        'Passenger exit of the cruise terminal where Oceania Marina is berthed',
      operationalNotes: [
        'Current pickup address: Herbert Walker Avenue, Southampton SO15 1HJ.',
        'Exact berth and terminal must be confirmed shortly before pickup.',
        '2 travelers · 2 checked bags · 2 hand-luggage items · saloon vehicle.',
      ],
      documentReferenceIds: ['document-southampton-heathrow-transfer'],
    },
    {
      id: 'event-heathrow-arrival-estimate',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Estimated arrival at Heathrow Terminal 5',
      startsAt: '2026-09-04T09:15:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-heathrow-terminal-5',
      timingVerification: 'ESTIMATED',
      operationalNotes: [
        'Planning estimate; keep this time editable in Trip.',
      ],
    },
    {
      id: 'event-heathrow-bag-drop',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Bag drop',
      timeZone: 'Europe/London',
      locationId: 'location-heathrow-terminal-5',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-heathrow-security',
      dayId: 'day-2026-09-04',
      kind: 'ACTIVITY',
      title: 'Security',
      timeZone: 'Europe/London',
      locationId: 'location-heathrow-terminal-5',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-return-flight',
      dayId: 'day-2026-09-04',
      kind: 'FLIGHT',
      title: 'Flight to Brussels',
      travelerIds: ['traveler-yoav', 'traveler-isabel'],
      startsAt: '2026-09-04T13:55:00+01:00',
      endsAt: '2026-09-04T16:10:00+02:00',
      timeZone: 'Europe/London',
      endTimeZone: 'Europe/Brussels',
      locationId: 'location-heathrow-terminal-5',
      transportId: 'transport-return-flight',
      organizer: 'British Airways',
      publicCode: 'BA386',
      bookingStatus: 'CONFIRMED',
      operationalNotes: [
        'Euro Traveller · Economy Plus.',
        'Checked baggage: 1 × 23 kg per person.',
        'Hand baggage: 1 cabin bag and 1 small handbag per person.',
        'Online check-in opens 24 hours before departure.',
        'Brussels Airport to home transport is not yet confirmed.',
      ],
    },
    {
      id: 'event-isafjordur-whale-nature',
      dayId: 'day-2026-08-24',
      kind: 'EXCURSION',
      title: 'Whale & Nature Watching',
      startsAt: '2026-08-24T09:30:00Z',
      endsAt: '2026-08-24T12:30:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-isafjordur',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'ISF-013',
    },
    {
      id: 'event-husavik-outbound-tender-report',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Report for outbound tender',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-outbound-tender-departure',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Tender departs',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-shore-arrival',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Arrive ashore',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-big-whale-safari',
      dayId: 'day-2026-08-25',
      kind: 'EXCURSION',
      title: 'GG2 Big Whale Safari & Puffins',
      startsAt: '2026-08-25T09:30:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      organizer: 'Gentle Giants',
      bookingType: 'INDEPENDENT',
      checkInAt: '2026-08-25T08:50:00Z',
      meetingContext: 'Gentle Giants Ticket Center, Húsavík',
      operationalNotes: [
        'Expected finish remains to be confirmed.',
      ],
      documentReferenceIds: ['document-husavik-whale-safari'],
    },
    {
      id: 'event-husavik-whale-boarding',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Boarding and put on overalls',
      startsAt: '2026-08-25T09:05:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      timingVerification: 'CONFIRMED',
      meetingContext: 'Gentle Giants Ticket Center, Húsavík',
    },
    {
      id: 'event-husavik-geosea-baths',
      dayId: 'day-2026-08-25',
      kind: 'EXCURSION',
      title: 'Húsavík & GeoSea Baths',
      startsAt: '2026-08-25T13:00:00Z',
      endsAt: '2026-08-25T15:30:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'HVK-006',
    },
    {
      id: 'event-husavik-return-tender-boarding',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Board return tender',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-return-tender-departure',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Return tender departs',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-back-onboard',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Back onboard',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-husavik-last-tender',
      dayId: 'day-2026-08-25',
      kind: 'ACTIVITY',
      title: 'Last tender',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-husavik',
      scheduleStatus: 'TO_BE_CONFIRMED',
    },
    {
      id: 'event-djupivogur-glacier-lagoon',
      dayId: 'day-2026-08-26',
      kind: 'EXCURSION',
      title: 'Glacier Lagoon, Diamond Beach & Stokksnes – Shore Excursion',
      startsAt: '2026-08-26T08:00:00Z',
      timeZone: 'Atlantic/Reykjavik',
      locationId: 'location-djupivogur',
      organizer: 'Arctic Shorex',
      bookingType: 'INDEPENDENT',
      meetingContext: 'Djúpavogsvegur, Djúpivogur',
      operationalNotes: ['Early tender coordination required'],
      documentReferenceIds: ['document-djupivogur-glacier-tour'],
    },
    {
      id: 'event-torshavn-vestmanna',
      dayId: 'day-2026-08-27',
      kind: 'EXCURSION',
      title: 'Vestmanna Sea Cliffs',
      startsAt: '2026-08-27T14:30:00+01:00',
      endsAt: '2026-08-27T18:30:00+01:00',
      timeZone: 'Atlantic/Faroe',
      locationId: 'location-torshavn',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'TAN-003',
    },
    {
      id: 'event-stornoway-isle-of-lewis',
      dayId: 'day-2026-08-29',
      kind: 'EXCURSION',
      title: 'Isle of Lewis Tour',
      startsAt: '2026-08-29T08:30:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-stornoway',
      organizer: 'Hebridean Isle Tours',
      bookingType: 'INDEPENDENT',
      bookingStatus: 'CONFIRMED',
      scheduleStatus: 'TO_BE_CONFIRMED',
      timingVerification: 'ESTIMATED',
      operationalNotes: [
        '08:30 is a TBC working assumption agreed with Hugh.',
        'Exact pickup point remains to be confirmed.',
        'Hugh verbally guaranteed return before ship departure.',
        'Exact return time remains to be confirmed.',
      ],
      meetingContext: 'Exact pickup point TBC',
      documentReferenceIds: ['document-stornoway-isle-of-lewis'],
      // The booking confirmation currently lists 10:00 and six hours. The
      // operator agreed by phone to an earlier cruise-compatible start and
      // return, but revised written timing is still pending.
    },
    {
      id: 'event-greenock-loch-lomond',
      dayId: 'day-2026-08-30',
      kind: 'EXCURSION',
      title: 'Loch Lomond and the Glengoyne Distillery',
      startsAt: '2026-08-30T13:45:00+01:00',
      endsAt: '2026-08-30T18:15:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-greenock',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'GRE-007',
    },
    {
      id: 'event-dublin-river-cruise',
      dayId: 'day-2026-08-31',
      kind: 'EXCURSION',
      title: 'River Cruise & Dublin Sights',
      startsAt: '2026-08-31T13:30:00+01:00',
      endsAt: '2026-08-31T17:30:00+01:00',
      timeZone: 'Europe/Dublin',
      locationId: 'location-dun-laoghaire',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'DLG-003',
    },
    {
      id: 'event-holyhead-penrhyn-castle',
      dayId: 'day-2026-09-01',
      kind: 'EXCURSION',
      title: 'Penrhyn Castle & Gardens',
      startsAt: '2026-09-01T12:30:00+01:00',
      endsAt: '2026-09-01T16:30:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-holyhead',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'HOY-003',
    },
    {
      id: 'event-cork-jameson',
      dayId: 'day-2026-09-02',
      kind: 'EXCURSION',
      title: 'Cork Orientation & Jameson Distillery',
      startsAt: '2026-09-02T09:30:00+01:00',
      endsAt: '2026-09-02T14:00:00+01:00',
      timeZone: 'Europe/Dublin',
      locationId: 'location-ringaskiddy',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'RIN-003',
    },
    {
      id: 'event-falmouth-st-ives',
      dayId: 'day-2026-09-03',
      kind: 'EXCURSION',
      title: 'St. Ives – The Idyllic Cornish Village',
      startsAt: '2026-09-03T10:00:00+01:00',
      endsAt: '2026-09-03T14:30:00+01:00',
      timeZone: 'Europe/London',
      locationId: 'location-falmouth',
      organizer: 'Oceania Cruises',
      bookingType: 'OCEANIA',
      publicCode: 'FLH-002',
    },
    {
      id: 'event-toscana-dinner',
      dayId: 'day-2026-08-25',
      kind: 'MEAL',
      title: 'Toscana',
      startsAt: '2026-08-25T20:00:00Z',
      timeZone: 'Atlantic/Reykjavik',
      bookingStatus: 'CONFIRMED',
      meetingContext: 'Shared table',
      mealType: 'DINNER',
      mealRestaurantId: 'toscana',
    },
    {
      id: 'event-red-ginger-dinner',
      dayId: 'day-2026-08-28',
      kind: 'MEAL',
      title: 'Red Ginger',
      startsAt: '2026-08-28T20:00:00+01:00',
      timeZone: 'Atlantic/Faroe',
      bookingStatus: 'CONFIRMED',
      meetingContext: 'Shared table',
      mealType: 'DINNER',
      mealRestaurantId: 'red-ginger',
    },
    {
      id: 'event-polo-grill-dinner',
      dayId: 'day-2026-08-31',
      kind: 'MEAL',
      title: 'Polo Grill',
      startsAt: '2026-08-31T19:30:00+01:00',
      timeZone: 'Europe/Dublin',
      bookingStatus: 'CONFIRMED',
      meetingContext: 'Shared table',
      mealType: 'DINNER',
      mealRestaurantId: 'polo-grill',
    },
    {
      id: 'event-jacques-dinner',
      dayId: 'day-2026-09-03',
      kind: 'MEAL',
      title: 'Jacques',
      startsAt: '2026-09-03T19:30:00+01:00',
      timeZone: 'Europe/London',
      bookingStatus: 'CONFIRMED',
      meetingContext: 'Shared table',
      mealType: 'DINNER',
      mealRestaurantId: 'jacques',
    },
  ],
  locations,
  transports: [
    {
      id: 'transport-home-brussels-airport',
      mode: 'PRIVATE_TRANSFER',
      label: 'Private car · airport drop-off',
      fromLocationId: 'location-home-ghent',
      toLocationId: 'location-brussels-airport',
    },
    {
      id: 'transport-outbound-flight',
      mode: 'AIR',
      label: 'Icelandair · BRU to KEF',
      fromLocationId: 'location-brussels-airport',
      toLocationId: 'location-keflavik-airport',
    },
    {
      id: 'transport-keflavik-hotel',
      mode: 'BUS',
      label: 'Reykjavík Excursions / Flybus',
      fromLocationId: 'location-keflavik-airport',
      toLocationId: 'location-hotel-viking',
    },
    {
      id: 'transport-hotel-ship',
      mode: 'PRIVATE_TRANSFER',
      label: 'Likely taxi · not yet arranged',
      fromLocationId: 'location-hotel-viking',
      toLocationId: 'location-reykjavik-cruise-terminal',
    },
    {
      id: 'transport-southampton-heathrow',
      mode: 'PRIVATE_TRANSFER',
      label: 'Confirmed saloon transfer',
      fromLocationId: 'location-southampton',
      toLocationId: 'location-heathrow-terminal-5',
    },
    {
      id: 'transport-return-flight',
      mode: 'AIR',
      label: 'British Airways · LHR to BRU',
      fromLocationId: 'location-heathrow-terminal-5',
      toLocationId: 'location-brussels-airport',
    },
  ],
  cruises: [
    {
      id: 'cruise-oceania-marina-2026',
      shipName: 'Oceania Marina',
      embarkationDate: '2026-08-23',
      disembarkationDate: '2026-09-04',
      portCallIds: portCalls.map(({ id }) => id),
    },
  ],
  portCalls,
  bookingReferences: [],
  documentReferences: [
    {
      id: 'document-precruise-hotel',
      title: 'Pre-cruise hotel confirmation',
      category: 'HOTEL',
      assetPath: '/documents/travel/precruise-hotel-confirmation.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-08-22',
      dayId: 'day-2026-08-22',
      description: 'One-night confirmation for the stay before embarkation.',
      actionLabel: 'Open hotel confirmation',
      offlineAvailable: true,
      verificationStatus: 'ISSUED',
    },
    {
      id: 'document-keflavik-reykjavik-flybus',
      title: 'Keflavík to Reykjavík Flybus voucher',
      category: 'TRANSFER',
      assetPath:
        '/documents/travel/keflavik-reykjavik-flybus-voucher.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-08-22',
      dayId: 'day-2026-08-22',
      locationId: 'location-reykjavik',
      description: 'Flexible airport-to-city transfer voucher for arrival day.',
      actionLabel: 'Open transfer voucher',
      offlineAvailable: true,
      verificationStatus: 'ISSUED',
    },
    {
      id: 'document-husavik-whale-safari',
      title: 'Húsavík whale safari confirmation',
      category: 'EXCURSION_CONFIRMATION',
      assetPath:
        '/documents/travel/husavik-whale-safari-confirmation.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-08-25',
      dayId: 'day-2026-08-25',
      locationId: 'location-husavik',
      description: 'Operator confirmation and practical check-in guidance.',
      actionLabel: 'Open excursion confirmation',
      offlineAvailable: true,
      verificationStatus: 'ISSUED',
    },
    {
      id: 'document-djupivogur-glacier-tour',
      title: 'Djúpivogur glacier tour ticket',
      category: 'EXCURSION_TICKET',
      assetPath:
        '/documents/travel/djupivogur-glacier-tour-ticket.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-08-26',
      dayId: 'day-2026-08-26',
      locationId: 'location-djupivogur',
      description: 'Travel ticket with the confirmed start and meeting point.',
      actionLabel: 'Open excursion ticket',
      offlineAvailable: true,
      verificationStatus: 'ISSUED',
    },
    {
      id: 'document-stornoway-isle-of-lewis',
      title: 'Stornoway Isle of Lewis confirmation',
      category: 'EXCURSION_CONFIRMATION',
      assetPath:
        '/documents/travel/stornoway-isle-of-lewis-confirmation.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-08-29',
      dayId: 'day-2026-08-29',
      locationId: 'location-stornoway',
      description: 'Original operator confirmation for the Isle of Lewis tour.',
      actionLabel: 'Open excursion confirmation',
      offlineAvailable: true,
      verificationStatus: 'ISSUED_WITH_SUPERSEDED_DETAILS',
      operationalNotice:
        'The time printed in this document is superseded. Departure and return remain to be confirmed in writing.',
    },
    {
      id: 'document-southampton-heathrow-transfer',
      title: 'Southampton to Heathrow transfer confirmation',
      category: 'TRANSFER',
      assetPath:
        '/documents/travel/southampton-heathrow-transfer.pdf',
      mimeType: 'application/pdf',
      associatedDate: '2026-09-04',
      dayId: 'day-2026-09-04',
      locationId: 'location-southampton',
      description: 'Confirmed private transfer after disembarkation.',
      actionLabel: 'Open transfer confirmation',
      offlineAvailable: true,
      verificationStatus: 'ISSUED',
    },
  ],
}
